### ISSUE TITLE
Why http://localhost:9999/uaa/login is not proxyfied

### ISSUE THREAD

**Issue by hlassiege** [spring-guides/tut-spring-security-and-angular-js#13]
I'm not sure I understood correctly the role Zuul is supposed to have.

I thought that zuul was supposed to be a reverse proxy so that every request to /login would be proxified to target localhost:9999/uaa/login

I've modified the routes like that : 

```
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
    login:
      path: /login/**
      url: http://localhost:9999/uaa/login
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    auth:
      path: /auth/**
      url: http://localhost:9999/uaa/
```

But the browser is always redirected to localhost:9999/uaa/login

Is it possible to have only localhost:8080 used for all endpoints with Zuul ?
